name: .NET

env:
 majorVersion: 2
 minorVersion: 0
 buildVersion: 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    needs: [test]
    
    steps:
      - run: echo "deployment"
  
  test:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    env:
      myVariable: "Basta 2021"
    steps:
      - run: echo "hello world ${{ env.myVariable }}"
  
  build:
    env:
      solutionpath: .\WinNetCoreApp\

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionpath }}
    - name: Find and Replace Action
      # You may pin to the exact commit or the version.
      # uses: nguyenvanuyn96/str-find-and-replace-action@c00a9cd8c5e4323363a1d5907e15c3a2b4ed9698
      uses: nguyenvanuyn96/str-find-and-replace-action@0.0.5
      env:
           version-number: ${{ env.majorVersion }}.${{ env.minorVersion }}.${{ env.buildVersion }}.${{ github.run_number }}
      with:
        # A regular expression of files to include in our find and replace
        include: 'AssemblyInfo.*'
        # The string we want to replace
        find: '1.0.0.0' 
        # The new string to replace with
        replace: ${{ env.version-number}}
        
     
      
    - name: Build
      run: dotnet build  ${{ env.solutionpath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionpath }} --no-build --verbosity normal
    - name: Upload dotnet results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet
        path: '.\WinNetCoreApp\WinNetCoreApp\bin\Debug'
      # Use always() to always run this step to publish test results when there are test failures
      #if: ${{ always() }}
