name: .NET

env:
 majorVersion: 2
 minorVersion: 0
 buildVersion: 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    needs: [test]
    
    steps:
      - run: echo "deployment"
  
  test:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    env:
      myVariable: "Basta 2021"
    steps:
      - run: echo "hello world ${{ env.myVariable }}"
  
  build:
    env:
      solutionpath: .\WinNetCoreApp\

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionpath }}
    - name: set-version-assemblyinfo
      # You may pin to the exact commit or the version.
      # uses: dannevesdantas/set-version-assemblyinfo@c7d09f193e84e1546d95b07afd3d0a6544978341
      uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
      env:
         version-number: ${{ env.majorVersion }}.${{ env.minorVersion }}.${{ env.buildVersion }}.${{ github.run_number }}
      with:
        # Folder location to search for AssemblyInfo.cs/.vb files
        # Version number to set on [AssemblyVersion] and [AssemblyFileVersion] attributes of AssemblyInfo.cs/.vb files
        version: ${{ env.version-number }}
      
    - name: Build
      run: dotnet build  ${{ env.solutionpath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionpath }} --no-build --verbosity normal
