name: .NETCoreWinAppDemo
#test

env:
 majorVersion: 2
 minorVersion: 0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
 issues: write
 contents: read
 checks: write

jobs:
  deploy:
    runs-on: windows-latest
    needs: [test]
    environment: Prod
    steps:
      - run: echo "deployment"
      - run: echo "my secret ${{ secrets.supersecret }}"
  
  test:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    env:
      myVariable: "Conference 2022"
    steps:
      - run: echo "hello world ${{ env.myVariable }}"
  
  build:
    env:
      solutionpath: .\WinNetCoreApp\

    runs-on: windows-latest
    # runs-on: [self-hosted, WPF]

    steps:
    - uses: actions/checkout@v2
    
    - run: echo runs only for pull requests
      if: github.event_name == 'pull_request'
    
    - name: Hello world action step
      id: hello
      uses: norschelMVP/demotest-hello-world-javascript-action@v1.11
      with:
        who-to-greet: 'Hallo Publikum'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x 
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionpath }}
      
    - name: AssemblyVersion - Modify version number
      uses: mingjun97/file-regex-replace@v1
      env:
           version-number: ${{ env.majorVersion }}.${{ env.minorVersion }}.${{ github.run_number }}.0
      with:
        regex: '<AssemblyVersion>[[0-9]+(\.([0-9]+|\*)){1,3}'
        replacement: '<AssemblyVersion>${{ env.version-number}}'
        flags: "gi"                  # Optional, defaults to "g"
        include: 'WinNetCoreApp.csproj'    # Optional, defaults to ".*"
        exclude: '.^'               # Optional, defaults to '.^'
        encoding: 'utf8'            # Optional, defaults to 'utf8'
        path: '.'                   # Optional, defaults to '.'
     
    - name: FileVersion - Modify version number
      uses: mingjun97/file-regex-replace@v1
      env:
           version-number: ${{ env.majorVersion }}.${{ env.minorVersion }}.${{ github.run_number }}.0
      with:
        regex: '<FileVersion>[[0-9]+(\.([0-9]+|\*)){1,3}'
        replacement: '<FileVersion>${{ env.version-number}}'
        flags: "gi"                  # Optional, defaults to "g"
        include: 'WinNetCoreApp.csproj'    # Optional, defaults to ".*"
        exclude: '.^'               # Optional, defaults to '.^'
        encoding: 'utf8'            # Optional, defaults to 'utf8'
        path: '.'                   # Optional, defaults to '.'
        
    - name: Version - Modify version number
      uses: mingjun97/file-regex-replace@v1
      env:
           version-number: ${{ env.majorVersion }}.${{ env.minorVersion }}.${{ github.run_number }}
      with:
        regex: '<Version>[[0-9]+(\.([0-9]+|\*)){1,2}'
        replacement: '<Version>${{ env.version-number}}'
        flags: "gi"                  # Optional, defaults to "g"
        include: 'WinNetCoreApp.csproj'    # Optional, defaults to ".*"
        exclude: '.^'               # Optional, defaults to '.^'
        encoding: 'utf8'            # Optional, defaults to 'utf8'
        path: '.'                   # Optional, defaults to '.'  
        
    - name: Build
      run: dotnet build  ${{ env.solutionpath }} --no-restore
      
    - name: Test
      run: dotnet test ${{ env.solutionpath }} --logger trx --no-build --verbosity normal  
    - name: Test Reporter
      uses: dorny/test-reporter@v1.6.0
      with:
        name: test
        reporter: dotnet-trx
        path: '**/*.trx'
      if: ${{ always() }}
    
    - name: Upload dotnet results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet
        path: '.\WinNetCoreApp\WinNetCoreApp\bin\Debug'
        retention-days: 90
      if: ${{ always() }}
      
    - name: Upload assemblyinfo results
      uses: actions/upload-artifact@v4.6.2
      with:
        name: assemblyinfo
        path: '.\WinNetCoreApp\WinNetCoreApp\obj'
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      
