name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    env:
      myVariable: "Basta 2021"
    steps:
      - run: echo "hello world ${{ env.myVariable }}"
  
  build:

    runs-on: windows-latest
    env:
      solutionpath: .\WinNetCoreApp\

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionpath }}
      
    - name: Build
      run: dotnet build  ${{ env.solutionpath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionpath }} --no-build --verbosity normal
