# This is a basic workflow that is manually triggered

name: Issue Created

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.issue.title }}"
      
    - name: OpenAI - Ask for a Chuck Norris answer
      uses: onmax/oai-createcompletion-githubaction@v1.0
      id: openai
      with:
        model: gpt-3.5-turbo-instruct
        prompt: "Chuck Norris muss zwangsweise ein IT Support Ticket mit dem Titel ${{ github.event.issue.title }} bearbeiten, er kann das unmögliche möglich machen, mag dieses aber heute nicht tun. Es wird ein epischer chuck norris spruch zum aufschieben des problems benötigt. Überzeuge den Ticketschreiber doch besser das problem selber zu lösen."
        max_tokens: 2000
        temperature: 1 # the temperature for the model. Optional
        openai_api_key: ${{ secrets.OPENAI_API_KEY }} # your openai api key
        
    - name: Show response from OpenAI - Chuck norris answer
      id: spruch
      run: |
        variable=$(echo '${{ steps.openai.outputs.response }}' | jq -r '.texts[] | sub("\\n"; "") | sub("\""; "")| sub("\""; "")')
        echo $variable
        variable=$(echo $variable | tr '\n' ' ')
        echo "Spruch=$variable" >> "$GITHUB_OUTPUT"

    - name: Add reactions
      uses: peter-evans/create-or-update-comment@v1
      with:
          reactions: heart, hooray, laugh
          body: "${{ steps.spruch.outputs.Spruch }}"
          issue-number: ${{ github.event.issue.number }}
              
    - name: AutoLabeller
      uses: actions/github-script@v4
      with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Postponed']
            })
            
    - name: Close Issue
      # You may pin to the exact commit or the version.
      # uses: peter-evans/close-issue@a700eac5bf2a1c7a8cb6da0c13f93ed96fd53dbe
      uses: peter-evans/close-issue@v1.0.3
      with:
        comment: '👋 Thanks for reporting! ... but unfortunately we do not have time for you at the moment. Don''t give up and just try again later.'
