name: OpenAI_Test

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main
    
jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: OpenAI CreateCompletion
      uses: onmax/oai-createcompletion-githubaction@v1.0
      id: openai
      with:
        model: text-davinci-003
        prompt: "Ich bin Chuck Norris und arbeite in der Agentur für Arbeit als Jobberater. Welchen Job würdest du Mike empfehlen. Er macht etwas mit IT und Cloud. Der Jobtitel soll im Chuck Norris Stil sein.Bitte gebe nur den Jobtitel aus."
        max_tokens: 100
        temperature: 1 # the temperature for the model. Optional
        openai_api_key: ${{ secrets.OPENAI_API_KEY }} # your openai api key

    # Examples on how to use the output
    - name: Show response from OpenAI CreateCompletion
      id: jobtitle
      run: |
        # echo '${{ steps.openai.outputs.response }}'
        variable=$(echo '${{ steps.openai.outputs.response }}' | jq -r '.texts[] | sub("\\n"; "") | sub("\""; "")| sub("\""; "")')
        echo $variable
        variable=$(echo $variable | tr '\n' ' ')
        echo "JobTitle=$variable" >> "$GITHUB_OUTPUT"
    - name: OpenAI CreateCompletion
      uses: onmax/oai-createcompletion-githubaction@v1.0
      id: openai2
      with:
        model: text-davinci-003
        prompt: "Ich brauche eine gute Aufgabenbeschreibung für Mike mit dem Jobtitel ${{ steps.jobtitle.outputs.JobTitle }} vor."
        max_tokens: 400
        temperature: 1 # the temperature for the model. Optional
        openai_api_key: ${{ secrets.OPENAI_API_KEY }} # your openai api key
        # Examples on how to use the output
        
    - name: Show response from OpenAI CreateCompletion - 2
      run: |
        variable=$(echo '${{ steps.openai2.outputs.response }}' | jq -r '.texts[] | sub("\\n"; "") | sub("\""; "")| sub("\""; "")')
        echo $variable
        variable=$(echo $variable | tr '\n' ' ')
        echo "JobTitle=$variable" >> "$GITHUB_OUTPUT"

        
