# This is a basic workflow that is manually triggered

name: Issue Created

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - uses: vadimdez/weather-action@11
      id: wetter
      with:
        lat: "49.4521"
        long: "11.0767"

    - name: Add reactions
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ steps.wetter.outputs.temperature  > 20}}
      with:
          reactions: heart, hooray, laugh
          body: "Bei ${{ steps.wetter.outputs.temperature }} Grad in ${{ steps.wetter.outputs.place }} würde ich auch ungern arbeiten."
          issue-number: ${{ github.event.issue.number }}
    
    - name: Add reactions
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ steps.wetter.outputs.temperature <= 20}} 
      with:
          reactions: heart, hooray, laugh
          body: "Bei ${{ steps.wetter.outputs.temperature }} Grad in ${{ steps.wetter.outputs.place }} würde ich auch gern arbeiten."
          issue-number: ${{ github.event.issue.number }}
          
    - name: AutoLabeller
      uses: actions/github-script@v4
      with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Postponed']
            })
    - name: Close Issue
      # You may pin to the exact commit or the version.
      # uses: peter-evans/close-issue@a700eac5bf2a1c7a8cb6da0c13f93ed96fd53dbe
      uses: peter-evans/close-issue@v1.0.3
      with:
        comment: '👋 Thanks for reporting! ... but unfortunately we do not have time for you at the moment. Don''t give up and just try again later.'
